hydra:
  run:
    dir: ./outputs/${default.output_folder}

output_folder: "test"

defaults:
  - data: petfinder
  - wandb: config 

model:
  train_batch_size: 64
  val_batch_size: 64
  num_epochs: 20
  num_workers: 2
  backbone: 'resnet50'
  pretrained: True
  head_1: 'linear'  # ['linear', 'MLP', "MLP_with_bn"]
  head_2: 'None' # ['None', 'linear', 'MLP', "MLP_with_bn", 'add_margin', 'arc_margin', 'sphere']
  loss: 'sbce'  # ['sbce', 'bce']

fold_type: "skfold"
n_fold: 5
input_channel: 3
seed: 42
gpuid: [0]
log_path: './logs/'
saved_path: './trained_model/'
log_interval: 1
save_top_model: 1
accumulate_grad_batches: 1
max_grad_norm: 1000
use_mixup: True

shd_para:
  scheduler: 'CosineAnnealingWarmRestarts'
  factor: 0.2 # ReduceLROnPlateau
  patience: 4 # ReduceLROnPlateau
  eps: 1e-6 # ReduceLROnPlateau
  T_max: 20 # CosineAnnealingLR
  T_0: 20 # CosineAnnealingWarmRestarts
  eta_min: 1e-5 # CosineAnnealingWarmRestarts
  lr: 1e-4
  min_lr: 1e-6

in_kaggle: False
